version: 2

jobs:
  build:
    working_directory: ~/zendesk-tickets-machine
    docker:
      - image: circleci/python:3.6.1
      - image: circleci/postgres:9.6.2
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: circle_test
    steps:
      - checkout
      - restore_cache:
          keys:
          - py-deps-{{ .Branch }}-{{ checksum "requirements/local.txt" }}
      - run:
          name: Install Dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements/local.txt
      - save_cache:
          paths:
            - ./venv
          key: py-deps-{{ .Branch }}-{{ checksum "requirements/local.txt" }}
      - run:
          name: Run Static Analysis
          command: |
            . venv/bin/activate
            flake8
      - run:
          name: Run Tests
          command: |
            . venv/bin/activate
            cd zendesk_tickets_machine && python manage.py test && cd ..
      - add_ssh_keys:
          fingerprints:
            - "40:ad:f8:e2:cc:2c:e6:64:bb:e6:51:c2:5b:7a:0e:74"
      - deploy:
          name: Deploy to Production
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              bash deploy.sh
            fi
